### ISSUE TITLE
Rename to `llm`

### ISSUE THREAD

**Issue by philpax** [rustformers/llm#136]
With our (hopefully) incoming support for #85 and #75, this crate is growing beyond just LLaMA support. At the same time, `llama_rs` is a little unwieldy as a crate name.

To accommodate this, I've taken the liberty of reserving the [llm](https://crates.io/crates/llm) crate name. Just before we release 0.1.0, `llama-rs` will be renamed to `llm`, and `llama-cli` will become `llm-cli` (but likely have the binary name `llm`, so you can do `llm bloom infer -m bloom_model -p "what's the capital of Virginia?"`).

Each model would be under its own feature flag, so you would only pay for what you use.

**Comment by setzer22** [comment]
As already discussed, I agree with the change on the crate name, since it's quite obvious that it's a rust project there. What I'm not sure about, is the github repo name. It's nice to have the crate and the repo be the same thing, but calling the repo just `llm` would feel like a bit too much.

If it weren't for the completely unrelated recent events, I would've suggested `rust-llm` for the repo, but let's better not...

**Comment by KerfuffleV2** [comment]
What about `llm-rs`? (Also if it's not a secret, what unrelated recent events?)

**Comment by philpax** [comment]
> What about llm-rs? 

For the repo name? Yeah that'd be fine, I just don't want `_rs` in the crate name itself

> (Also if it's not a secret, what unrelated recent events?)

https://www.reddit.com/r/rust/comments/12e7tdb/rust_trademark_policy_feedback_form/

**Comment by katopz** [comment]
- `llm` is fine for crate because it's in `Rust` context/domain already. so no `rs` needed.
- `llm-rs` for repos is good idea because it's in github with many other languages (easier while search).

Aww, naming is hard!

**Comment by philpax** [comment]
I've updated all of the crates and the README, but I'll need @setzer22 to give me full permissions to update the repo name.

I'm still leaning towards `rustformers/llm` for now - I think `rustformers` is sufficiently evocative
