### ISSUE TITLE
Modular sampler

### ISSUE THREAD

**Issue by philpax** [rustformers/llm#318]
This was alluded to in #308 and in the code itself, but the existing `TopPTopK` sampler has the following logical structure:

- For each logit,
  - Replace the value of the logit with the one specified in the bias if present
  - Otherwise, if in the last N tokens, apply a repetition penalty including temperature scaling to the logit
  - Otherwise, apply temperature scaling to the logit
  - Store the logit
- Apply Top-P Top-K sampling to the constructed logit list

This ends up baking in the repetition penalty / temperature scaling / token bias logic into the sampler, which isn't ideal for re-use.

What I'd like to do is redesign this sampler, so that all of these pieces are modular and you can swap them out or remove them entirely where applicable:
- token bias/override strategy (#308)
- repetition penalty strategy
- temperature scaling
- sampling strategy

The existing `TopPTopK` sampler would then be an instantiation of this modular sampler with a Top-P Top-K sampler and options for the rest where applicable.

**Comment by KerfuffleV2** [comment]
#327 may be relevant here. I made a crate with various types of samplers, including all the ones llama.cpp currently supports like Mirostat.

**Comment by philpax** [comment]
That's fantastic! I'll have a closer look when I have some free time, and think about how integration might work. Nice work as always 🙂

**Comment by KerfuffleV2** [comment]
I looked at it a bit. Currently it's going to be pretty hard to do be cause right now the samplers want to own all their state/resources (so you can't easily have something like a `Default` instance since a sampler would contain the RNG source for example).

I'm working on a more flexible approach where a resource object that can have stuff like the RNG or last tokens is passed at the point sampling actually occurs. This will hopefully enable something like building a chain of samplers from a string description or stuff like that.
